### ISSUE TITLE
Persona being retired

### ISSUE THREAD

**Issue by mpress** [southlondonmakerspace/membership-system#14]
@unknowndomain @thisislawatts Mozilla pulling the plug on persona in November ...
http://www.i-programmer.info/news/81-web-general/9341-mozilla-persona-signs-out.html

should focus my mind.

**Comment by unknowndomain** [comment]
Wow.

**Comment by thisislawatts** [comment]
:hankey: #facepalm

**Comment by thisislawatts** [comment]
@mpress @unknowndomain what day would work best to have a roundtable about what needs doing? I am focusing on the WordPress theme at the moment but hoping to get a launchable version in place for next week

**Comment by unknowndomain** [comment]
Erm... Next week, maybe one evening?

**Comment by mpress** [comment]
We could have a quick catchup after the air muscles talk on Monday.

Or I can do the tail end of next week ... would the µmeet on Thursday be
too distracting if we did it then? I'm happy to do Friday - otherwise will
have to be the week after which currently looks free.

I should start freeing up v soon to put some proper energy into this.
'fraid I've not found a lot of time to look at it since Tom and I last sat
down.

**Comment by thisislawatts** [comment]
Let's go for Thursday next week with µmeet, if it does get a bit distracting we can always go next door to Canopy or something. I was seeing this initially as a todo list divide and conquer session rather than eyes down coding..

![cynxfyjw8ae6ert](https://cloud.githubusercontent.com/assets/472589/12324494/c5493bc2-baba-11e5-95f1-ade8091b706a.jpg)

**Comment by unknowndomain** [comment]
Good with me.

**Comment by mpress** [comment]
@unknowndomain @thisislawatts I have broken the internet at work today. Not sure I'll be able to get out of here in time to get to the space tonight - and if I do don't think I will want to think about code. Sorry.

**Comment by thisislawatts** [comment]
No problem @mpress. I am having similar issues with a BT phoneline today. @unknowndomain if you're still up for it would be good to talk through the system as it stands, and put together an initial list of jobs ahead of catching up together next week?

Then a bit of gentle 🔥flaming🔥 on southlondonmakerspace/wordpress-theme#1 so we can get that ready to go go go

**Comment by unknowndomain** [comment]
:(

See you tonight


Kind Regards


Tom Lynch

**Comment by unknowndomain** [comment]
Done
