### ISSUE TITLE
Login Email addresses should not be case sensitive

### ISSUE THREAD

**Issue by naxxfish** [southlondonmakerspace/membership-system#198]
When logging in, the email address entered should not have to match the case of the email address in the DB.

**Comment by naxxfish** [comment]
Should be noted here that where a DB already exists, there would have been the possibility to have two accounts with the same email address with different cases... this fix only works for people signing up after this change has been applied.

**Comment by unknowndomain** [comment]
Yes, and we should go through the database looking for this, a simple bit of grepping text into a file then running unique would tell us where there are issues.

Kind Regards


Tom Lynch
