### ISSUE TITLE
Log logged in user + IP of user by default for all Bunyan logging

### ISSUE THREAD

**Issue by unknowndomain** [southlondonmakerspace/membership-system#276]

**Comment by naxxfish** [comment]
This will have an added dependency on the reverse proxy configuration - retrieving the IP will either be through checking `req.connection.remoteAddress` or by looking at a header set by the proxy - for example:

```
proxy_set_header    X-Forwarded-For  $proxy_add_x_forwarded_for;
```

And then checking this header in the request.
