### ISSUE TITLE
Configuration option for running behind a reverse proxy

### ISSUE THREAD

**Issue by naxxfish** [southlondonmakerspace/membership-system#286]
As per [Express behind a proxy](http://expressjs.com/en/guide/behind-proxies.html) there is a configuration option that's required to be set if you want the remote IP to be reported correctly, namely:
```
app.set('trust proxy', true);
```

We should probably provide a config option to turn this on.

**Comment by unknowndomain** [comment]
We setup Nginx to set `X-Forwarded-For: <ip>` but with trust proxy set to 'loopback' it didn't work.

More work needed to test this and make it work.

**Comment by naxxfish** [comment]
Could we see the exact nginx config that was used for this ?
