### ISSUE TITLE
create backlog

### ISSUE THREAD

**Issue by mpress** [southlondonmakerspace/membership-system#9]
We need a (prioritised) list of what needs to be done so we aren't tripping over each other/ all working on the same problem.

**Comment by thisislawatts** [comment]
+1 It would be great to help out if I can.

Is it worth bringing any issues across from [southlondonmakerspace/slm-site/issues](https://github.com/southlondonmakerspace/slm-site/) or have the requirements moved on a fair bit since those were raised?

**Comment by unknowndomain** [comment]
Total rewrite

**Comment by unknowndomain** [comment]
Well we should aim to meet with @mpress to go through it.

**Comment by mpress** [comment]
Still catching up on your latest changes but happy to sit down whenever (Thursday night bad this week).

**Comment by thisislawatts** [comment]
I am happy to help out however I can.

Would it be worth me spending some time on the theme so it's a little closer to the main site http://southlondonmakerspace.org/? <http://southlondonmakerspace.org/?>

**Comment by unknowndomain** [comment]
Sure if you fancy… new one is at http://slms.wpengine.com, the design is all pretty close to done, just needs implementing.

Kind Regards


Tom Lynch

**Comment by thisislawatts** [comment]
Ah blimey didn't realise there was a whole other main site as well. You got an ideal launch for all of this new stuff (other than ASAP)? 
------------------------
Luke Watts

E : luke@thisis.la
S : thisislawatts
T : 07885910261

LA Code & Design LTD
Company No : 07848589

**Comment by unknowndomain** [comment]
Nope, just as and when… 

The membership system only handles memberships, the website is a blog and front page for us.

Kind Regards


Tom Lynch

**Comment by thisislawatts** [comment]
Is there anything I can help with on the Theme?

**Comment by unknowndomain** [comment]
Continuing the development, it needs the blog, page, and comments doing, and there is some work on compatibility.

**Comment by unknowndomain** [comment]
This isn't an issue?
